### PR TITLE
columns collapse

### PR DESCRIPTION
**Pull request by rita-moreira**
created a new story inside Columns - columnsGrouping where you can test

### CODE REVIEW

**Comment by VeraRibeiro** [comment]
@rita-moreira the collapse and expand is working fine, but it's not possible to write inside the Name2 or City2 columns, if we do it it goes to the next column

(if I write on Name2 it goes to City, if I write in City2 it goes to Country)
Screenshot 2021-09-15 at 11 39 00

**Comment by rita-moreira** [comment]
> @rita-moreira the collapse and expand is working fine, but it's not possible to write inside the Name2 or City2 columns, if we do it it goes to the next column
> 
> (if I write on Name2 it goes to City, if I write in City2 it goes to Country)
> Screenshot 2021-09-15 at 11 39 00

right!! I didn't test that sorry, I will check

**Comment by rita-moreira** [comment]
> > @rita-moreira the collapse and expand is working fine, but it's not possible to write inside the Name2 or City2 columns, if we do it it goes to the next column
> > (if I write on Name2 it goes to City, if I write in City2 it goes to Country)
> > Screenshot 2021-09-15 at 11 39 00
> 
> right!! I didn't test that sorry, I will check

notice now in Row Grouping example, that we can't change also the nested rows

**Comment by VeraRibeiro** [comment]
@rita-moreira I think it works fine now!

**Comment by rita-moreira** [comment]
> @rita-moreira I think it works fine now!

nice!!

**Pull request merged**
