### PR TITLE
remove clearAll

### PR DESCRIPTION
**Pull request by rita-moreira**
remove clearAll

### CODE REVIEW

**Comment by underfisk** [comment]
This will not fix the issue, the cache is used for the `CellMeasurer`, when we need to recompute the sizes if you dont clear then its not going to calculate later, we can test with this but you have sufficient demos on Apollo to see this behaviour. In order to see how important this is, just go over a cell, type a lot and then see that if you omit this it will not set the height/width correctly of that cell

**Comment by rita-moreira** [comment]
> This will not fix the issue, the cache is used for the `CellMeasurer`, when we need to recompute the sizes if you dont clear then its not going to calculate later, we can test with this but you have sufficient demos on Apollo to see this behaviour. In order to see how important this is, just go over a cell, type a lot and then see that if you omit this it will not set the height/width correctly of that cell

yeah you are right! And what do you think of instead of clearAll(), change this to       cacheRef.current.clear(coords.rowIndex, coords.colIndex), which means calculating only the updated cell?

**Comment by underfisk** [comment]
> > This will not fix the issue, the cache is used for the `CellMeasurer`, when we need to recompute the sizes if you dont clear then its not going to calculate later, we can test with this but you have sufficient demos on Apollo to see this behaviour. In order to see how important this is, just go over a cell, type a lot and then see that if you omit this it will not set the height/width correctly of that cell
> 
> yeah you are right! And what do you think of instead of clearAll(), change this to cacheRef.current.clear(coords.rowIndex, coords.colIndex), which means calculating only the updated cell?

The problem is that you can't predict the cell that was affected just using the current coordinates, because in top what if the update is performed with a pusher event and its not even in the selected coordinate?

**Comment by rita-moreira** [comment]
> > > This will not fix the issue, the cache is used for the `CellMeasurer`, when we need to recompute the sizes if you dont clear then its not going to calculate later, we can test with this but you have sufficient demos on Apollo to see this behaviour. In order to see how important this is, just go over a cell, type a lot and then see that if you omit this it will not set the height/width correctly of that cell
> > 
> > 
> > yeah you are right! And what do you think of instead of clearAll(), change this to cacheRef.current.clear(coords.rowIndex, coords.colIndex), which means calculating only the updated cell?
> 
> The problem is that you can't predict the cell that was affected just using the current coordinates, because in top what if the update is performed with a pusher event and its not even in the selected coordinate?

oki, so please delete this PR, I don't know what else I can do to fix this error.

**Pull request closed without merging**
